### ISSUE TITLE
Integer values are parsed incorrectly

### ISSUE THREAD

**Issue by dvejmz** [LloydLabs/librini#2]
# Description
Integer values are parsed incorrectly: the first digit of the value is always flipped to the number '1', for instance, this

```ini
ssh_port=99
```

Would be parsed as '19' instead of '99'. I've tried with a few different numbers of different lengths and it seems to always be the first digit which gets changed to be a "1".

I'm quite happy to look at this and submit a PR if you don't have time to investigate it.

# Reproduction Steps
1. Compile the library
1. Link it into the `server_config.c` file in the examples directory of this repository.
1. Run the executable

# Expected

```
Name of main server: honeypot
Please change the port from 99 to a number above 1024
```

# Actual

```
Name of main server: honeypot
Please change the port from 19 to a number above 1024
```

# Environment
OS: Fedora 26
Kernel version: 4.13.4-200.fc26.x86_64
Compiled with clang 4.0.1

**Comment by LloydLabs** [comment]
I'll fix this later on, I think I know the issue.
